export const STORAGE_KEYS = {
  TRADE_HISTORY: 'trade_history',
  ADDRESS_BOOK: 'address_book',
  USDC_WALLET_ID: 'usdc_wallet_id',
  USDC_WALLET: 'usdc_wallet',
  ARGBOT_TESTNET: 'argbot_testnet',
  BINANCE_KEY: 'binance_key',
  BINANCE_SECRET: 'binance_secret',
  BINANCE_KEY_TESTNET: 'binance_key_testnet',
  BINANCE_SECRET_TESTNET: 'binance_secret_testnet',
  BINANCE_EUR_IBAN: 'binance_eur_iban',
  BINANCE_EUR_NAME: 'binance_eur_name',
  BINANCE_EUR_BIC: 'binance_eur_bic',
  BINANCE_BANK_NAME: 'binance_bank_name',
  BINANCE_BANK_ADDRESS: 'binance_bank_address',
  USER_EMAIL: 'user_email',
  SERVICE_FEE: 'service_fee',
  FEE_WHITELIST: 'fee_whitelist',
  ARGBOT_NOTIF_BANNER_ENABLED: 'argbot_notif_banner_enabled',
  ARGBOT_NOTIF_OPT_IN_DISMISSED: 'argbot_notif_opt_in_dismissed',
  ARGBOT_NOTIFICATIONS_ENABLED: 'argbot_notifications_enabled',
  DRIVE_FILE_ID: 'drive_file_id',
  RATE_ALERT_CONFIG: 'rate_alert_config',
} as const;
